### ISSUE TITLE
I can't use the program 

### ISSUE THREAD

**Issue by ohretro** [HerbieHSSO/OverMark#1]
I can't use the program. 🤨🤨🤨🤨🤨🤨🤨
When I go through the setup, the setup says:
"The OverMark Program is made for users, using the program without permission from the author is prohibited." 🤡🤡🤡🤡🤡
Guys what do I do???????😭😭😭😭😭😭😭😭😭😭😭

**Comment by HerbieHSSO** [comment]
THANK YOU FOR INSTALL, I DIDN ASKED + AND I CARE + COPE

**Comment by ffirenn** [comment]
OhRetro...
